using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Team_Project
{
    public static class SpritePath
    {
        // Mario
        public const string SmallMarioIdleRightPath = "Player/mario/marioIdleRight";
        public const string SmallMarioIdleLeftPath = "Player/mario/marioIdleLeft";
        public const string BigMarioIdleRightPath = "Player/mario/bigMarioIdleRight";
        public const string BigMarioIdleLeftPath = "Player/mario/bigMarioIdleLeft";
        public const string FireMarioIdleRightPath = "Player/mario/fireMarioIdleRight";
        public const string FireMarioIdleLeftPath = "Player/mario/fireMarioIdleLeft";
        public const string SmallMarioRunningRightPath = "Player/mario/marioRunningRight";
        public const string SmallMarioRunningLeftPath = "Player/mario/marioRunningLeft";
        public const string BigMarioRunningRightPath = "Player/mario/bigMarioRunningRight";
        public const string BigMarioRunningLeftPath = "Player/mario/bigMarioRunningLeft";
        public const string FireMarioRunningRightPath = "Player/mario/fireMarioRunningRight";
        public const string FireMarioRunningLeftPath = "Player/mario/fireMarioRunningLeft";
        public const string SmallMarioJumpingRightPath = "Player/mario/marioJumpRight";
        public const string SmallMarioJumpingLeftPath = "Player/mario/marioJumpLeft";
        public const string BigMarioJumpingRightPath = "Player/mario/bigMarioJumpRight";
        public const string BigMarioJumpingLeftPath = "Player/mario/bigMarioJumpLeft";
        public const string FireMarioJumpingRightPath = "Player/mario/fireMarioJumpRight";
        public const string FireMarioJumpingLeftPath = "Player/mario/fireMarioJumpLeft";
        public const string BigMarioCrouchingRightPath = "Player/mario/bigMarioCrouchRight";
        public const string BigMarioCrouchingLeftPath = "Player/mario/bigMarioCrouchLeft";
        public const string FireMarioCrouchingRightPath = "Player/mario/fireMarioCrouchRight";
        public const string FireMarioCrouchingLeftPath = "Player/mario/fireMarioCrouchLeft";
        public const string MarioDeadRightPath = "Player/mario/marioDeadRight";
        public const string MarioDeadLeftPath = "Player/mario/marioDeadLeft";
        public const string SmallMarioTurningLeftPath = "Player/mario/marioTurningLeft";
        public const string SmallMarioTurningRightPath = "Player/mario/marioTurningRight";
        public const string BigMarioTurningLeftPath = "Player/mario/bigMarioTurningLeft";
        public const string BigMarioTurningRightPath = "Player/mario/bigMarioTurningRight";
        public const string FireMarioTurningLeftPath = "Player/mario/fireMarioTurningLeft";
        public const string FireMarioTurningRightPath = "Player/mario/fireMarioTurningRight";
        public const string BigSmallMarioRightPath = "Player/mario/BigSmallMarioRight";
        public const string BigSmallMarioLeftPath = "Player/mario/BigSmallMarioLeft";
        public const string BigMarioSwimIdleRightPath = "Player/mario/bigMarioSwimIdleRight";
        public const string BigMarioSwimIdleLeftPath = "Player/mario/bigMarioSwimIdleLeft";
        public const string SmallMarioSwimIdleRightPath = "Player/mario/marioSwimIdleRight";
        public const string SmallMarioSwimIdleLeftPath = "Player/mario/marioSwimIdleLeft";
        public const string FireMarioFireballRightPath = "Player/mario/fireMarioFireballRight";
        public const string FireMarioFireballLeftPath = "Player/mario/fireMarioFireballLeft";
        public const string SmallMarioWinningLegDownRightPath = "Player/mario/SmallMarioWinningLegDownRight";
        public const string SmallMarioWinningLegUpRightPath = "Player/mario/SmallMarioWinningLegUpRight";
        public const string SmallMarioWinningLegDownLeftPath = "Player/mario/SmallMarioWinningLegDownLeft";
        public const string SmallMarioWinningLegUpLeftPath = "Player/mario/SmallMarioWinningLegUpLeft";
        public const string BigMarioWinningArmDownRightPath = "Player/mario/BigMarioWinningArmDownRight";
        public const string BigMarioWinningArmUpRightPath = "Player/mario/BigMarioWinningArmUpRight";
        public const string BigMarioWinningArmDownLeftPath = "Player/mario/BigMarioWinningArmDownLeft";
        public const string BigMarioWinningArmUpLeftPath = "Player/mario/BigMarioWinningArmUpLeft";
        public const string FireMarioWinningArmDownRightPath = "Player/mario/FireMarioWinningArmDownRight";
        public const string FireMarioWinningArmUpRightPath = "Player/mario/FireMarioWinningArmUpRight";
        public const string FireMarioWinningArmDownLeftPath = "Player/mario/FireMarioWinningArmDownLeft";
        public const string FireMarioWinningArmUpLeftPath = "Player/mario/FireMarioWinningArmUpLeft";
        public const string IceMarioIdleRightPath = "Player/mario/iceMarioIdleRight";
        public const string IceMarioIdleLeftPath = "Player/mario/iceMarioIdleLeft";
        public const string IceMarioRunningRightPath = "Player/mario/iceMarioRunningRight";
        public const string IceMarioRunningLeftPath = "Player/mario/iceMarioRunningLeft";
        public const string IceMarioCrouchRightPath = "Player/mario/iceMarioCrouchRight";
        public const string IceMarioCrouchLeftPath = "Player/mario/iceMarioCrouchLeft";
        public const string IceMarioJumpingRightPath = "Player/mario/iceMarioJumpRight";
        public const string IceMarioJumpingLeftPath = "Player/mario/iceMarioJumpLeft";
        public const string IceMarioTurningRightPath = "Player/mario/iceMarioTurningRight";
        public const string IceMarioTurningLeftPath = "Player/mario/iceMarioTurningLeft";
        public const string IceMarioIceballRightPath = "Player/mario/iceMarioIceballRight";
        public const string IceMarioIceballLeftPath = "Player/mario/iceMarioIceballLeft";
        public const string IceMarioWinningArmDownRightPath = "Player/mario/iceMarioSittingRight";
        public const string IceMarioWinningArmUpRightPath = "Player/mario/iceMarioSlidingRight";
        public const string IceMarioWinningArmDownLeftPath = "Player/mario/iceMarioSittingLeft";
        public const string IceMarioWinningArmUpLeftPath = "Player/mario/iceMarioSlidingLeft";

        // Luigi
        public const string SmallLuigiIdleRightPath = "Player/luigi/luigiIdleRight";
        public const string SmallLuigiIdleLeftPath = "Player/luigi/luigiIdleLeft";
        public const string BigLuigiIdleRightPath = "Player/luigi/bigLuigiIdleRight";
        public const string BigLuigiIdleLeftPath = "Player/luigi/bigLuigiIdleLeft";
        public const string FireLuigiIdleRightPath = "Player/luigi/fireMarioIdleRight";
        public const string FireLuigiIdleLeftPath = "Player/luigi/fireMarioIdleLeft";
        public const string SmallLuigiRunningRightPath = "Player/luigi/luigiRunningRight";
        public const string SmallLuigiRunningLeftPath = "Player/luigi/luigiRunningLeft";
        public const string BigLuigiRunningRightPath = "Player/luigi/bigLuigiRunningRight";
        public const string BigLuigiRunningLeftPath = "Player/luigi/bigLuigiRunningLeft";
        public const string FireLuigiRunningRightPath = "Player/luigi/fireMarioRunningRight";
        public const string FireLuigiRunningLeftPath = "Player/luigi/fireMarioRunningLeft";
        public const string SmallLuigiJumpingRightPath = "Player/luigi/luigiJumpRight";
        public const string SmallLuigiJumpingLeftPath = "Player/luigi/luigiJumpLeft";
        public const string BigLuigiJumpingRightPath = "Player/luigi/bigLuigiJumpRight";
        public const string BigLuigiJumpingLeftPath = "Player/luigi/bigLuigiJumpLeft";
        public const string FireLuigiJumpingRightPath = "Player/luigi/fireMarioJumpRight";
        public const string FireLuigiJumpingLeftPath = "Player/luigi/fireMarioJumpLeft";
        public const string BigLuigiCrouchingRightPath = "Player/luigi/bigLuigiCrouchRight";
        public const string BigLuigiCrouchingLeftPath = "Player/luigi/bigLuigiCrouchLeft";
        public const string FireLuigiCrouchingRightPath = "Player/luigi/fireMarioCrouchRight";
        public const string FireLuigiCrouchingLeftPath = "Player/luigi/fireMarioCrouchLeft";
        public const string LuigiDeadRightPath = "Player/luigi/luigiDeadRight";
        public const string LuigiDeadLeftPath = "Player/luigi/luigiDeadLeft";
        public const string SmallLuigiTurningLeftPath = "Player/luigi/luigiTurningLeft";
        public const string SmallLuigiTurningRightPath = "Player/luigi/luigiTurningRight";
        public const string BigLuigiTurningLeftPath = "Player/luigi/bigLuigiTurningLeft";
        public const string BigLuigiTurningRightPath = "Player/luigi/bigLuigiTurningRight";
        public const string FireLuigiTurningLeftPath = "Player/luigi/fireMarioTurningLeft";
        public const string FireLuigiTurningRightPath = "Player/luigi/fireMarioTurningRight";
        public const string BigSmallLuigiRightPath = "Player/luigi/BigSmallLuigiRight";
        public const string BigSmallLuigiLeftPath = "Player/luigi/BigSmallLuigiLeft";
        public const string BigLuigiSwimIdleRightPath = "Player/luigi/bigLuigiSwimIdleRight";
        public const string BigLuigiSwimIdleLeftPath = "Player/luigi/bigLuigiSwimIdleLeft";
        public const string SmallLuigiSwimIdleRightPath = "Player/luigi/luigiSwimIdleRight";
        public const string SmallLuigiSwimIdleLeftPath = "Player/luigi/luigiSwimIdleLeft";
        public const string FireLuigiFireballRightPath = "Player/luigi/fireMarioFireballRight";
        public const string FireLuigiFireballLeftPath = "Player/luigi/fireMarioFireballLeft";
        public const string SmallLuigiWinningLegDownRightPath = "Player/luigi/SmallLuigiWinningLegDownRight";
        public const string SmallLuigiWinningLegUpRightPath = "Player/luigi/SmallLuigiWinningLegUpRight";
        public const string SmallLuigiWinningLegDownLeftPath = "Player/luigi/SmallLuigiWinningLegDownLeft";
        public const string SmallLuigiWinningLegUpLeftPath = "Player/luigi/SmallLuigiWinningLegUpLeft";
        public const string BigLuigiWinningArmDownRightPath = "Player/luigi/BigLuigiWinningArmDownRight";
        public const string BigLuigiWinningArmUpRightPath = "Player/luigi/BigLuigiWinningArmUpRight";
        public const string BigLuigiWinningArmDownLeftPath = "Player/luigi/BigLuigiWinningArmDownLeft";
        public const string BigLuigiWinningArmUpLeftPath = "Player/luigi/BigLuigiWinningArmUpLeft";
        public const string FireLuigiWinningArmDownRightPath = "Player/luigi/FireMarioWinningArmDownRight";
        public const string FireLuigiWinningArmUpRightPath = "Player/luigi/FireMarioWinningArmUpRight";
        public const string FireLuigiWinningArmDownLeftPath = "Player/luigi/FireMarioWinningArmDownLeft";
        public const string FireLuigiWinningArmUpLeftPath = "Player/luigi/FireMarioWinningArmUpLeft";
        public const string IceLuigiIdleRightPath = "Player/luigi/iceMarioIdleRight";
        public const string IceLuigiIdleLeftPath = "Player/luigi/iceMarioIdleLeft";
        public const string IceLuigiRunningRightPath = "Player/luigi/iceMarioRunningRight";
        public const string IceLuigiRunningLeftPath = "Player/luigi/iceMarioRunningLeft";
        public const string IceLuigiCrouchRightPath = "Player/luigi/iceMarioCrouchRight";
        public const string IceLuigiCrouchLeftPath = "Player/luigi/iceMarioCrouchLeft";
        public const string IceLuigiJumpingRightPath = "Player/luigi/iceMarioJumpRight";
        public const string IceLuigiJumpingLeftPath = "Player/luigi/iceMarioJumpLeft";
        public const string IceLuigiTurningRightPath = "Player/luigi/iceMarioTurningRight";
        public const string IceLuigiTurningLeftPath = "Player/luigi/iceMarioTurningLeft";
        public const string IceLuigiIceballRightPath = "Player/luigi/iceMarioIceballRight";
        public const string IceLuigiIceballLeftPath = "Player/luigi/iceMarioIceballLeft";
        public const string IceLuigiWinningArmDownRightPath = "Player/luigi/iceMarioSittingRight";
        public const string IceLuigiWinningArmUpRightPath = "Player/luigi/iceMarioSlidingRight";
        public const string IceLuigiWinningArmDownLeftPath = "Player/luigi/iceMarioSittingLeft";
        public const string IceLuigiWinningArmUpLeftPath = "Player/luigi/iceMarioSlidingLeft";

        //Bowser
        public const string BowserIdleRight = "Player/bowser/bowseridleright";
        public const string BowserRunningRight = "Player/bowser/bowserrunningright";
        public const string BowserIdleLeft = "Player/bowser/bowseridleleft";
        public const string BowserRunningLeft = "Player/bowser/bowserrunningleft";
        public const string BigBowserRunningLeft = "Player/bowser/bigbowserrunleft";
        public const string BigBowserRunningRight = "Player/bowser/bigbowserrunright";
        public const string BigBowserIdleLeft = "Player/bowser/bigbowserfaceleft";
        public const string BigBowserIdleRight = "Player/bowser/bigbowserfaceright";
        public const string GigaBowserRunningLeft = "Player/bowser/GigaBowserrunleft2";
        public const string GigaBowserRunningRight = "Player/bowser/GigaBowserrunright2";
        public const string GigaBowserIdleLeft = "Player/bowser/GigaBowseridleleft";
        public const string GigaBowserIdleRight = "Player/bowser/GigaBowseridleright";
        public const string SmallBowserBreathLeft = "Player/bowser/smallbowserbreathleft";
        public const string SmallBowserBreathRight = "Player/bowser/smallbowserbreathright";
        public const string BigBowserBreathLeft = "Player/bowser/bigbowserbreathleft";
        public const string BigBowserBreathRight = "Player/bowser/bigbowserbreathright";
        public const string GigaBowserBreathLeft = "Player/bowser/GigaBowserfireleft";
        public const string GigaBowserBreathRight = "Player/bowser/GigaBowserfireright";

        // Enemies
        public const string GoombaWalkPath = "Enemies/goombawalk";
        public const string GoombaSquishPath = "Enemies/goombasquish";
        public const string GoombaKilledPath = "Enemies/goombaKilled";
        public const string KoopaWalkLeftPath = "Enemies/koopawalkleft";
        public const string KoopaShellPath = "Enemies/koopaShell";
        public const string KoopaKilledPath = "Enemies/koopakilled";
        public const string KoopaWalkRightPath = "Enemies/koopawalkright";
        public const string PirahnaChompPath = "Enemies/pirahnachomp";

        // Items
        public const string OneUPMushroom1APath = "Items/1UPMushroom1A";
        public const string Coin1Path = "Items/Coin1";
        public const string Coin2Path = "Items/Coin2";
        public const string FireFlowerPath = "Items/FireFlower1";
        public const string IceFlowerPath = "Items/IceFlower1";
        public const string Starman1Path = "Items/Starman1";
        public const string SuperMushroom1APath = "Items/SuperMushroom1A";

        //  Blocks
        public const string BlockExplode2Path = "Blocks/blockexplode2";
        public const string HiddenBlockPath = "Blocks/HiddenBlock";
        public const string QuestionBlockPath = "Blocks/QuestionBlock";
        public const string RedBlockPath = "Blocks/RedBlock";
        public const string RegularFloorBlockPath = "Blocks/RegularFloorBlock";
        public const string StepPyramidBlockPath = "Blocks/StepPyramidBlock";
        public const string UndergroundBlockPath = "Blocks/UndergroundBlock";
        public const string UndergroundFloorBlockPath = "Blocks/UndergroundFloorBlock";
        public const string UsedBlockPath = "Blocks/UsedBlock";
        public const string SnowOnBlockPath = "Blocks/SnowOnBlock";
        public const string IceBlock1616Path = "Blocks/IceBlock1616";
        public const string IceBlock1622Path = "Blocks/IceBlock1622";
        public const string IceBlock1624Path = "Blocks/IceBlock1624";

        // Screens
        public const string MainscreenPath = "GameStates/mainscreen";
        public const string DotPath = "GameStates/dot";
        public const string LivesLeftMarioScreenPath = "GameStates/livesleftscreenMario";
        public const string LivesLeftLuigiScreenPath = "GameStates/livesleftscreenLuigi";
        public const string LivesLeftBowserScreenPath = "GameStates/livesleftscreenBowser";
        public const string GameOverScreenPath = "GameStates/gameoverscreen";
        public const string HighScoreScreenPath = "GameStates/highscorescreen";
        public const string PauseScreenPath = "GameStates/pausescreen";
        public const string ConfirmationScreenPath = "GameStates/confirmationscreen";
        public const string OptionMenuPath = "GameStates/optionmenu";
        public const string LevelSelectScreenPath = "GameStates/levelselectscreen";

        // Misc
        public const string SmallPipePath = "Misc/SmallPipe";
        public const string MediumPipePath = "Misc/MediumPipe";
        public const string LargePipePath = "Misc/LargePipe";
        public const string HorizontalLPipeLeftStandPath = "Misc/HorizontalLPipeLeftStand";
        public const string HorizontalLPipeLeftInPath = "Misc/HorizontalLPipeLeftIn";
        public const string SmallHillPath = "Misc/SmallHill";
        public const string BigHillPath = "Misc/BigHill";
        public const string OneBushPath = "Misc/OneBush";
        public const string TwoBushPath = "Misc/TwoBush";
        public const string ThreeBushPath = "Misc/ThreeBush";
        public const string OneCloudPath = "Misc/OneCloud";
        public const string TwoCloudsPath = "Misc/TwoClouds";
        public const string ThreeCloudsPath = "Misc/ThreeClouds";
        public const string MarioFireballPath = "Misc/MarioFireball";
        public const string MarioIceballPath = "Misc/MarioIceball";
        public const string IceballExplosionPath = "Misc/IceballExplosion";
        public const string FireBallWorksPath = "Misc/FireBallWorks";
        public const string HUDFontPath = "Misc/HUDFont";
        public const string LivesLeftFontPath = "Misc/LivesLeftFont";
        public const string HUDCoinPath = "Misc/HUDCoin";
        public const string SmallCastlePath = "Misc/SmallCastle";
        public const string FlagPath = "Misc/Flag";
        public const string PolePath = "Misc/Pole";
        public const string CastleFlagPath = "Misc/CastleFlag";
        public const string OptionsFontPath = "Misc/OptionsFont";
        public const string HighScoreFontPath = "Misc/HighScoreFont";
        public const string EmberLeftPath = "Misc/bowseremberleft";
        public const string EmberRightPath = "Misc/bowseremberright";
        public const string FFLeftPath = "Misc/flamethrowerright";
        public const string FFRightPath = "Misc/flamethrowerleft";
        public const string MFLeftPath = "Misc/megafireleft3";
        public const string MFRightPath = "Misc/megafireright3";
        public const string FlameShotLeftPath = "Misc/ShootingFireLeft";
        public const string FlameShotDownPath = "Misc/ShootingFireDown";
        public const string FlameShotRightPath = "Misc/ShootingFireRight";
        public const string FlyingBlockPath = "Blocks/RedBlock";
    }
}
